stages:
  extract_flight:
    cmd: python src/data_processing/extract_flight_data.py
    deps:
      - config/paths.yaml
      - data/raw/raw_flight/archive.zip
      - src/data_processing/extract_flight_data.py
    outs:
      - data/extracted/extracted_flight/

  process_flight:
    cmd: python src/data_processing/process_flight_data.py
    deps:
      - config/paths.yaml
      - config/process/base.yaml
      - src/data_processing/process_flight_data.py
    outs:
      - data/processed/processed_flight/

  download_noaa:
    cmd: python src/data_processing/download_noaa_data.py
    deps:
      - config/paths.yaml
      - config/process/base.yaml
      - src/data_processing/download_noaa_data.py
    outs:
      - data/raw/raw_noaa/

  extract_noaa:
    cmd: python src/data_processing/extract_noaa_data.py
    deps:
      - config/paths.yaml
      - config/process/base.yaml
      - src/data_processing/extract_noaa_data.py
    outs:
      - data/extracted/extracted_noaa/

  process_noaa:
    cmd: python src/data_processing/process_noaa_data.py
    deps:
      - config/paths.yaml
      - config/process/base.yaml
      - src/data_processing/process_noaa_data.py
    outs:
      - data/processed/processed_noaa/

  # combine:
  #   cmd: python src/combine_parquet.py
  #   deps:
  #     - config/main.yaml
  #     - data/extracted
  #     - src/combine_parquet.py
  #   outs:
  #     - data/processed/combined_data.parquet