stages:
  extract_flight:
    cmd: python src/extract_zip.py
    deps:
      - config/main.yaml
      - data/raw/archive.zip
      - src/extract_zip.py
    outs:
      - data/extracted

  download_noaa:
    cmd: python src/download_noaa_data.py
    deps:
      - config/main.yaml
      - src/download_noaa_data.py
    outs:
      - data/noaa_raw/

  extract_noaa:
    cmd: python src/extract_noaa_data.py
    deps:
      - config/main.yaml
      - src/extract_noaa_data.py
    outs:
      - data/noaa_extracted/

  # combine:
  #   cmd: python src/combine_parquet.py
  #   deps:
  #     - config/main.yaml
  #     - data/extracted
  #     - src/combine_parquet.py
  #   outs:
  #     - data/processed/combined_data.parquet