models:
  linear_regression:
    exclude_features: []
    target: "DepDelayMinutes"
    params: {}

  histgradientboosting_regression:
    exclude_features: []
    target: "DepDelayMinutes"
    params:
      max_iter: 100
      learning_rate: 0.1
      max_depth: 5
    param_grid:
      learning_rate: [0.01, 0.1, 0.2]
      max_depth: [3, 5, 10]
      min_samples_leaf: [1, 5, 10]

  logistic_regression:
    exclude_features: []
    target: "DepDel15"
    params:
      max_iter: 200
      solver: "lbfgs"
    param_grid:
      penalty: ["l1", "l2"]
      C: [0.1, 1, 10]
      solver: ["liblinear"]

  sgd_classifier:
    exclude_features: []
    target: "DepDel15"
    params:
      max_iter: 1000
    param_grid:
      loss: ["hinge"]
      alpha: [0.0001, 0.001, 0.01]
      max_iter: [1000, 2000]
