models:
  linear_regression:
    exclude_features: ["id", "timestamp"]
    target: "delay_minutes"
    params: {}

  logistic_regression:
    exclude_features: ["id", "timestamp"]
    target: "delayed"
    params:
      max_iter: 200
      solver: "lbfgs"

  histgradientboosting_regression:
    exclude_features: ["id", "timestamp"]
    target: "delay_minutes"
    params:
      max_iter: 100
      learning_rate: 0.1
      max_depth: 5

  sgd_classifier:
    exclude_features: ["id", "timestamp"]
    target: "delayed"
    params:
      loss: "log"
      max_iter: 1000
