paths:
  raw_data: data/raw/archive.zip
  extracted_data: data/extracted
  processed_data: data/processed/combined_data.parquet
  noaa_data_raw: "data/noaa_raw"

noaa_data:
  base_url: "https://www.ncei.noaa.gov/pub/data/ghcn/daily/by_year/"
  years: [2018, 2019, 2020, 2021, 2022]
  delete_gz: true  # Set to false if you want to keep the .gz files