paths:
  airport_station_data: data/provided/airport_station_key.csv
  raw_flight_data: data/raw/raw_flight/archive.zip
  raw_noaa_data: data/raw/raw_noaa
  extracted_flight_data: data/extracted/extracted_flight
  extracted_noaa_data: data/extracted/extracted_noaa
  processed_flight_data: data/processed/processed_flight
  processed_noaa_data: data/processed/processed_noaa
  final_by_year: data/final/by_year
  final_combined: data/final/final_data.parquet
  combined_parquet_file: data/extracted/combined_data.parquet
